REGISTER_URL = 'https://stellarburgers.nomoreparties.site/api/auth/register'
LOGIN_URL = 'https://stellarburgers.nomoreparties.site/api/auth/login'
PATCH_URL = 'https://stellarburgers.nomoreparties.site/api/auth/user'
INGREDIENTS_URL = 'https://stellarburgers.nomoreparties.site/api/ingredients'
GET_ORDER_URL = 'https://stellarburgers.nomoreparties.site/api/orders'
CREATE_ORDER_URL = 'https://stellarburgers.nomoreparties.site/api/orders'
